### ISSUE TITLE
Bug: Survey fails to open in mobile app via QR Code 

### ISSUE THREAD

**Issue by TariUMD** [pjdohertygis/FirstResponderSARSurvey#4]
Survey fails to open in Survey123 app from QR Code but opens successfully in the browser. 
App Version: Survey 123 v3.3.64
Device: Google Pixel Android v8.0.0

**Comment by TariUMD** [comment]
![Survey123_Error](https://user-images.githubusercontent.com/33467757/54790240-d1387480-4c0b-11e9-957d-59fa05d3b3f6.png)

**Comment by pjdohertygis** [comment]
@TariUMD which QR Code app are you using? or are you using just the camera?

**Comment by TariUMD** [comment]
> @TariUMD which QR Code app are you using? or are you using just the camera?

@pjdohertygis  - I am using QR Scanner 1.3.4.6 by Kaspersky Lab

**Comment by pjdohertygis** [comment]
@TariUMD - can you test again with the latest? https://www.arcgis.com/apps/MapSeries/index.html?appid=71f7501c36d34dfdaf8a81b424806033&entry=6

**Comment by TariUMD** [comment]
@pjdohertygis - It fails to open using the The QR Scanner app. This may be an issue with that particular app.  I was able to get it to work using the updated camera app for my Google Pixel by [enabling lens suggestions.](https://android.gadgethacks.com/how-to/scan-qr-codes-your-pixels-camera-app-0192157/)

**Comment by pjdohertygis** [comment]
Ok I will close this issue but perhaps we can add this to documentation somewhere
